# PowerShell-Graph- CreateMeetingInSpecifiedPersonsCalendar.ps1
# Code initially generated by CoPilot then modified.

<#
.SYNOPSIS
  Create a meeting (calendar event with attendees) in another user's calendar using Microsoft Graph
  with application (client credentials) authentication.

.DESCRIPTION
  - Acquires an app-only access token from Entra ID (OAuth2 v2.0 token endpoint)
  - Calls Microsoft Graph:
      POST https://graph.microsoft.com/v1.0/users/{id|UPN}/calendar/events
    to create an event in the target user's default calendar. [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
  - If attendees are included, Exchange will send meeting invitations to them. [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
  - Optional: set isOnlineMeeting + onlineMeetingProvider to create a Teams meeting join URL. [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)

.NOTES
  Required Microsoft Graph application permission:
    - Calendars.ReadWrite (Application) [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
    - Don't forget to grant Admin Consent.
#>

# -----------------------------
# 1) PARAMETERS YOU FILL IN
# -----------------------------

$TenantId     = "YOUR_TENANT_ID_GUID"
$ClientId     = "YOUR_APP_CLIENT_ID_GUID"
$ClientSecret = "YOUR_APP_CLIENT_SECRET"

# The user you want to create the meeting "as" (i.e., the meeting will be in THEIR calendar)
# Can be UPN (user@domain.com) or the user object id.
$OrganizerUserIdOrUpn = "alexw@contoso.com"

# Meeting details
$Subject  = "Project Sync (created by app-only Graph)"
$TimeZone = "Pacific Standard Time"   # Must be a timezone supported by the mailbox server. [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)

# Use ISO-like strings (local wall clock) that match the specified time zone.
# Example: "2026-03-05T13:00:00"
$StartLocal = "2026-03-05T13:00:00"
$EndLocal   = "2026-03-05T13:30:00"

# Attendees (email addresses). Add as many as you want.
$AttendeeEmails = @(
  "sam@contoso.com",
  "pat@contoso.com"
)
 
# Optional location / body
$LocationDisplayName = "Conf Room 3"
$BodyHtml = "<p>Agenda:</p><ul><li>Status updates</li><li>Risks</li><li>Next steps</li></ul>"

# Optional: create as a Teams online meeting
$CreateTeamsOnlineMeeting = $true

# -----------------------------
# 2) TOKEN ACQUISITION (APP-ONLY)
# -----------------------------

function Get-GraphAppOnlyToken {
  param(
    [Parameter(Mandatory)] [string] $TenantId,
    [Parameter(Mandatory)] [string] $ClientId,
    [Parameter(Mandatory)] [string] $ClientSecret
  )

  # v2 token endpoint for client credentials (application flow)
  $TokenUri = "https://login.microsoftonline.com/$TenantId/oauth2/v2.0/token"

  # For client credentials with Graph, use scope = https://graph.microsoft.com/.default
  # This tells Entra ID to issue a token containing the app's *application permissions* that have admin consent.
  $TokenBody = @{
    client_id     = $ClientId
    client_secret = $ClientSecret
    grant_type    = "client_credentials"
    scope         = "https://graph.microsoft.com/.default"
  }

  try {
    $TokenResponse = Invoke-RestMethod -Method Post -Uri $TokenUri -Body $TokenBody -ContentType "application/x-www-form-urlencoded"
    return $TokenResponse.access_token
  }
  catch {
    throw "Failed to acquire token. $($_.Exception.Message)"
  }
}

$AccessToken = Get-GraphAppOnlyToken -TenantId $TenantId -ClientId $ClientId -ClientSecret $ClientSecret

# -----------------------------
# 3) BUILD EVENT (MEETING) PAYLOAD
# -----------------------------

# Convert attendee emails into Graph attendee objects.
# Each attendee object includes emailAddress + type ("required" or "optional")
$Attendees = @()
foreach ($email in $AttendeeEmails) {
  $Attendees += @{
    type        = "required"
    emailAddress = @{
      address = $email
      name    = $email
    }
  }
}

# Build the event object according to Microsoft Graph "event" schema.
# start/end are dateTimeTimeZone objects. [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
$EventPayload = @{
  subject = $Subject

  body = @{
    contentType = "HTML"
    content     = $BodyHtml
  }

  start = @{
    dateTime = $StartLocal
    timeZone = $TimeZone
  }

  end = @{
    dateTime = $EndLocal
    timeZone = $TimeZone
  }

  location = @{
    displayName = $LocationDisplayName
  }

  attendees = $Attendees

  # allowNewTimeProposals defaults to true when creating an event, but we set explicitly for clarity. [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
  allowNewTimeProposals = $true
}

# Optional: make it a Teams online meeting (calendar-backed).
# Graph docs show enabling online meeting on event creation using:
# isOnlineMeeting = true, onlineMeetingProvider = "teamsForBusiness" [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
if ($CreateTeamsOnlineMeeting) {
  $EventPayload.isOnlineMeeting       = $true
  $EventPayload.onlineMeetingProvider = "teamsForBusiness"
}

# Convert the PowerShell hashtable payload into JSON.
# Use a high Depth because nested objects (attendees/start/end/body) require it.
$EventJson = $EventPayload | ConvertTo-Json -Depth 20

# -----------------------------
# 4) CALL GRAPH: CREATE EVENT IN TARGET USER CALENDAR
# -----------------------------

# IMPORTANT:
# This is the key "on behalf of another user" part:
# We POST to /users/{OrganizerUserIdOrUpn}/calendar/events, not /me/... [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)

# Encode the UPN safely for URL usage.
$EncodedUser = [Uri]::EscapeDataString($OrganizerUserIdOrUpn)

$GraphUri = "https://graph.microsoft.com/v1.0/users/$EncodedUser/calendar/events"

$Headers = @{
  Authorization = "Bearer $AccessToken"
  "Content-Type" = "application/json"

  # Optional: asks Graph to express start/end in this timezone in the response. [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
  Prefer = "outlook.timezone=""$TimeZone"""
}

try {
  $CreatedEvent = Invoke-RestMethod -Method Post -Uri $GraphUri -Headers $Headers -Body $EventJson

  Write-Host "Event created successfully." -ForegroundColor Green
  Write-Host "  Id:      $($CreatedEvent.id)"
  Write-Host "  Subject: $($CreatedEvent.subject)"
  Write-Host "  WebLink: $($CreatedEvent.webLink)"

  # If Teams meeting creation worked, joinUrl is usually found here: onlineMeeting.joinUrl [1](https://learn.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0)
  if ($CreatedEvent.onlineMeeting -and $CreatedEvent.onlineMeeting.joinUrl) {
    Write-Host "  Teams Join URL: $($CreatedEvent.onlineMeeting.joinUrl)" -ForegroundColor Cyan
  }
  else {
    Write-Host "  Teams Join URL: (not present) - if you requested Teams, verify licensing/policies for the organizer mailbox."
  }
}
catch {
  # Graph error bodies are helpful. Try to print them.
  Write-Host "Failed to create event." -ForegroundColor Red
  Write-Host "HTTP error: $($_.Exception.Message)" -ForegroundColor Red

  # If available, dump response body for troubleshooting.
  if ($_.Exception.Response -and $_.Exception.Response.GetResponseStream()) {
    $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
    $respBody = $reader.ReadToEnd()
    Write-Host "Response body:" -ForegroundColor Yellow
    Write-Host $respBody
  }

  throw
}
